### ISSUE TITLE
App Crashes in Android 4.1.1

### ISSUE THREAD

**Issue by AruLNadhaN** [Hariofspades/IncDec#3]
If i remove the `IncDecImageButton` widget from the layout. The App works perfectly. I don't know what's wrong!

Here is the stack trace

```
         android.view.InflateException: Binary XML file line #86: Error inflating class com.hariofspades.incdeclibrary.IncDecImageButton
                                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
```

LAYOUT

```
 <LinearLayout
            android:id="@+id/quantity_picker"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:orientation="horizontal"
            android:layout_centerInParent="true">

            <com.hariofspades.incdeclibrary.IncDecImageButton
                android:id="@+id/incdec"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                app:textSizeB="18"
                app:textColorB="@color/darkGreen"
                app:leftDrawableTintB="@color/darkGreen"
                app:rightDrawableTintB="@color/darkGreen"
                app:leftDrawableB="@drawable/ic_remove_circle_outline_black_24dp"
                app:rightDrawableB="@drawable/ic_add_circle_outline_black_24dp"/>

        </LinearLayout>
```

**Comment by Hariofspades** [comment]
Hi @AruLNadhaN 

I've provided the fix. Please try
```groovy
compile 'com.hariofspades.IncDec:incdeclibrary:0.0.5'
```
and let me know

**Comment by AruLNadhaN** [comment]
It's working. Thanks!

**Comment by AruLNadhaN** [comment]
App is working perfectly on devices over 5.0.
If I remove the below two lines from the IncDecImageButton. It is working on 4.1 also without any crash. 

```
                app:leftDrawableB="@drawable/ic_remove_circle_outline_black_24dp"
                app:rightDrawableB="@drawable/ic_add_circle_outline_black_24dp"
```


**item_shot.xml**

```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="wrap_content"
    android:layout_height="200dp"
    android:layout_marginBottom="@dimen/shot_item_margin_bottom"
    android:layout_marginTop="@dimen/shot_item_margin"
    android:background="@drawable/bg_card"
    android:elevation="2dp">

    <ImageView
        android:id="@+id/image_shot"
        android:layout_width="80dp"
        android:layout_height="80dp"
        android:layout_centerHorizontal="true"
        android:scaleType="centerCrop" />

    <me.arulnadhan.grocerycorecommon.utils.MaterialBadgeTextView
        android:id="@+id/badge"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentRight="true"
        app:mbtv_backgroundColor="@color/shopColorPrimary"
        android:textColor="@color/white"
        android:textSize="14sp"
        android:text="In Cart"/>

    <LinearLayout
        android:id="@+id/layout_header"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@+id/image_shot"
        android:layout_above="@+id/divider"
        android:layout_centerInParent="true"
        android:gravity="center"
        android:orientation="vertical">

        <TextView
            android:id="@+id/text_price"
            fontPath="fonts/Sofia-Pro-Regular.otf"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:ellipsize="end"
            android:textSize="16sp"
            android:textColor="@color/shopColorPrimaryDark"
            tools:text="₹ 10.22" />

        <TextView
            android:id="@+id/text_title"
            fontPath="fonts/Sofia-Pro-Regular.otf"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:paddingLeft="4dp"
            android:paddingRight="4dp"
            android:text="Spinach Spinach"
            android:textSize="14sp"
            android:maxLines="2"
            android:ellipsize="end"
            android:gravity="center"
            android:textColor="@color/black" />

        <TextView
            android:id="@+id/text_unit"
            fontPath="fonts/Sofia-Pro-Regular.otf"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:paddingBottom="2dp"
            android:textSize="14sp"
            android:text="1.22 lbs"
            android:textColor="@color/grey" />

    </LinearLayout>

    <View
        android:id="@+id/divider"
        android:layout_width="match_parent"
        android:layout_height="4dp"
        android:layout_above="@+id/layout_footer"
        android:background="@color/divider" />

    <RelativeLayout
        android:id="@+id/layout_footer"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:paddingTop="4dp"
        android:paddingBottom="4dp"
        android:layout_alignParentBottom="true">

        <LinearLayout
            android:id="@+id/quantity_picker"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:orientation="horizontal"
            android:layout_centerInParent="true">

            <com.hariofspades.incdeclibrary.IncDecImageButton
                android:id="@+id/incdec"
                android:layout_width="wrap_content"
                android:layout_height="32dp"
                app:textSizeB="16"
                app:textColorB="@color/shopColorPrimaryDark"
                app:leftDrawableTintB="@color/shopColorPrimaryDark"
                app:rightDrawableTintB="@color/shopColorPrimaryDark"
                app:leftDrawableB="@drawable/ic_remove_circle_outline_black_24dp"
                app:rightDrawableB="@drawable/ic_add_circle_outline_black_24dp"/>

        </LinearLayout>

        <LinearLayout
            android:id="@+id/add_cart"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:orientation="horizontal"
            android:layout_centerInParent="true">

            <ImageView
                android:id="@+id/cart_icon"
                android:layout_width="24dp"
                android:layout_height="24dp"
                android:layout_gravity="center"
                android:scaleType="centerCrop"
                android:tint="@color/shopColorPrimaryDark"
                app:srcCompat="@drawable/ic_shopping_basket_black_24dp" />

            <TextView
                android:id="@+id/text_addcart"
                fontPath="fonts/Sofia-Pro-Regular.otf"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:textSize="16sp"
                android:padding="5dp"
                android:text="Add to Cart"
                android:textColor="@color/shopColorPrimaryDark"
                android:textStyle="bold" />

        </LinearLayout>

    </RelativeLayout>
</RelativeLayout>
```

**ADAPTER**

```
public class MoviesAdapter extends RecyclerView.Adapter<MoviesAdapter.MyViewHolder> {

    private List<Product> mItems;
    Context mContext;

    public MoviesAdapter(List<Product> items, Context context) {
        mContext = context;
        mItems = items;
    }

    @Override
    public MyViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View itemView = LayoutInflater.from(parent.getContext()).inflate(R.layout.item_shot, parent, false);
        return new MyViewHolder(itemView);
    }

    public class MyViewHolder extends RecyclerView.ViewHolder {

        ImageView prodImage;
        TextView prodPrice;
        TextView prodName;
        TextView prodUnit;
        View mAddCart;
        View mPickerView;
        IncDecImageButton mPicker;

        public MyViewHolder(View itemView) {
            super(itemView);
            prodImage = (ImageView) itemView.findViewById(R.id.image_shot);
            prodPrice = (TextView) itemView.findViewById(R.id.text_price);
            prodName = (TextView) itemView.findViewById(R.id.text_title);
            prodUnit = (TextView) itemView.findViewById(R.id.text_unit);
            mPickerView = (View) itemView.findViewById(R.id.quantity_picker);
            mPicker = (IncDecImageButton) itemView.findViewById(R.id.incdec);
            mAddCart = (View) itemView.findViewById(R.id.add_cart);

            mPicker.setConfiguration(LinearLayout.HORIZONTAL, IncDecImageButton.TYPE_INTEGER,
                    IncDecImageButton.DECREMENT, IncDecImageButton.INCREMENT);
            mPicker.setupValues(1, 20, 1, 1);
            mPicker.enableLongPress(true, true, 200);
        }

    }

    Double getPrice(Product item) {
        if (item.getProductDisplayPrice().isEmpty())
            return Double.valueOf(item.getProductMRP());
        else
            return Double.valueOf(item.getProductDisplayPrice());
    }

    @Override
    public void onBindViewHolder(MyViewHolder shotViewHolder, int position) {
        Product item = mItems.get(position);
        shotViewHolder.prodName.setText(StringUtils.capitalize(item.getProductName()));
        shotViewHolder.prodPrice.setText("₹ " + String.format("%.2f", getPrice(item)));
        shotViewHolder.prodUnit.setText(item.getProductUnit());
    }

    @Override
    public int getItemCount() {
        return mItems.size();
    }
}
```

LOG CAT
```
03-03 04:03:57.073 4058-4058/E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     android.view.InflateException: Binary XML file line #97: Error inflating class com.hariofspades.incdeclibrary.IncDecImageButton
                                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                         at owse.MoviesAdapter.onCreateViewHolder(MoviesAdapter.java:33)
                                                                         at owse.MoviesAdapter.onCreateViewHolder(MoviesAdapter.java:21)
                                                                         at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6319)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5507)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5392)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5388)
                                                                         at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
                                                                         at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                         at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
                                                                         at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
                                                                         at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                         at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3535)
                                                                         at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3264)
                                                                         at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3796)
                                                                         at android.view.View.layout(View.java:13754)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                         at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
                                                                         at android.view.View.layout(View.java:13754)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                         at android.view.View.layout(View.java:13754)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                         at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
                                                                         at android.view.View.layout(View.java:13754)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                         at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
                                                                         at android.view.View.layout(View.java:13754)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                         at android.view.View.layout(View.java:13754)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
                                                                         at android.view.View.layout(View.java:13754)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                         at android.view.View.layout(View.java:13754)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
                                                                         at android.view.View.layout(View.java:13754)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                         at android.view.View.layout(View.java:13754)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                         at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1866)
                                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1687)
                                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:998)
                                                                     	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:
```

**Comment by AruLNadhaN** [comment]
Crash was due to the below issue http://stackoverflow.com/questions/36867298/using-android-vector-drawables-on-pre-lollipop-crash
